In [1]:
import magpylib as magpy
import numpy as np
import matplotlib.pyplot as plt
import coil as co
import plotly.graph_objects as go

In [31]:
#some big number
step=1000
#turn
turn=10
lenght=5
magic=turn/lenght
dl=np.linspace(0,turn,step)
vertex=np.c_[np.cos(2*np.pi*dl),np.sin(2*np.pi*dl),((dl-turn/2)/magic)]
coil1 = magpy.current.Line(
    current=1,
    vertices=vertex,
    position=(0,0,0)   
)
co2Pos=(0,0,10)
coil2 = magpy.current.Line(
    current=1,
    position=co2Pos,
    vertices=vertex+co2Pos
)

coil2.rotate_from_euler(180,"x")


Line(id=1925773937440)

[[ 9.98022777e-01  6.28532900e-02 -2.49499499e+00]
 [ 9.92098928e-01  1.25458030e-01 -2.48998999e+00]
 [ 9.82251877e-01  1.87566653e-01 -2.48498498e+00]
 ...
 [ 9.92098928e-01 -1.25458030e-01  2.48998999e+00]
 [ 9.98022777e-01 -6.28532900e-02  2.49499499e+00]
 [ 1.00000000e+00 -2.44929360e-15  2.50000000e+00]]


In [33]:
b_on_c2 = coil1.getB(coil2.vertices)

print(b_on_c2)


[[ 0.00391795 -0.00134695  0.01691383]
 [ 0.00380665 -0.00110395  0.01691383]
 [ 0.00368107 -0.00086839  0.01691365]
 ...
 [ 0.00046379 -0.00032526  0.00337677]
 [ 0.00044831 -0.00029656  0.00337676]
 [ 0.00043111 -0.0002689   0.00337676]]


In [54]:
for idx, vert in enumerate(coil2.vertices):
    #print(np.cross(vert[idx+2]-vert[idx],b_on_c2[idx+1])) 
    



1.0
0.9980227772604111
0.9920989278611685
0.9822518773417481
0.9685205653265598
0.9509592915403253
0.9296375010827771
0.9046395098117981
0.8760641709209582
0.8440244840299503
0.8086471483337551
0.7700720615775812
0.7284517668388609
0.6839508493039655
0.6367452854250606
0.5870217470308186
0.5349768631428518
0.4808164424169648
0.42475465928404793
0.3670132070089654
0.30782042101662793
0.24741037595200252
0.18602196004469201
0.12389793043845522
0.06128395322131638
-0.001572368047584636
-0.06442247147276828
-0.12701781974687876
-0.1891108829779164
-0.2504561175326985
-0.31081093702577123
-0.36993667161404314
-0.42759951180366895
-0.4835714330369443
-0.5376310974029872
-0.5895647289064391
-0.6391669588329847
-0.6862416378687335
-0.7306026117619886
-0.7720744574600859
-0.8104931768102918
-0.8457068450815561
-0.8775762117425775
-0.9059752511204399
-0.930791660762262
-0.9519273055291265
-0.9692986056661355
-0.9828368673139948
-0.992488554155135
-0.9982154991201608
-0.9999950553174459
-0.997820